services:
  app_proxy:
    environment:
      APP_HOST: qubic-lite-node_edge
      APP_PORT: 8080
      PROXY_AUTH_ADD: "true"
      PROXY_AUTH_WHITELIST: "/api/*,/swagger/*"
    networks:
      - default
      - umbrel_main_network

  qubic-lite-node_edge:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on: 
      - qubic-lite-node_ui
      - qubic-lite-node_core
    volumes:
      - ${APP_DATA_DIR}/edge/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - umbrel_main_network
    # Zusätzliche DNS-Auflösung für Tor-Services
    extra_hosts:
      - "host.docker.internal:host-gateway"

  qubic-lite-node_core:
    image: andyqus/qubic-lite-node:core-v1.0.40
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:9090
      - ASPNETCORE_ENVIRONMENT=Production
      - TorProxy=socks5://tor:9050
      - ASPNETCORE_DATAPROTECTION__KEYRING__PATH=/app/data/keys
      - ASPNETCORE_DATAPROTECTION__APPLICATIONNAME=QubicLite-Core
      - DATA_DIR=/app/data
      - OnionHostnamePath=/tor-host/hostname
      - NETWORK_TIMEOUT=60000
      - TOR_CONNECTION_TIMEOUT=120000
    volumes:
      - ${APP_DATA_DIR}/core-data:/app/data
      - /home/umbrel/umbrel/tor/data/app-qubic-lite-node:/tor-host:ro
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --no-proxy -qO- http://127.0.0.1:9090/api/health > /dev/null || exit 1"]
    #   interval: 30s
    #   timeout: 15s
    #   retries: 5
    #   start_period: 60s
    healthcheck:
      test: ["CMD-SHELL", "(command -v wget >/dev/null && wget -qO- http://127.0.0.1:9090/api/health >/dev/null) || (command -v curl >/dev/null && curl -fsS http://127.0.0.1:9090/api/health >/dev/null) || (command -v busybox >/dev/null && busybox wget -qO- http://127.0.0.1:9090/api/health >/dev/null) || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - default
      - umbrel_main_network

  qubic-lite-node_ui:
    image: andyqus/qubic-lite-node:ui-v1.0.40
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_DATAPROTECTION__KEYRING__PATH=/app/data/keys
      - ASPNETCORE_DATAPROTECTION__APPLICATIONNAME=QubicLite-UI
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - CORE_API_URL=http://qubic-lite-node_core:9090
      - OnionHostnamePath=/tor-host/hostname
      - DATA_DIR=/app/data
    volumes:
      - ${APP_DATA_DIR}/ui-data:/app/data
      - /home/umbrel/umbrel/tor/data/app-qubic-lite-node:/tor-host:ro
    depends_on:
      qubic-lite-node_core:
        condition: service_healthy  # Warten auf gesunden Core-Service
    networks:
      - default
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true