version: "3.8"

services:
  app_proxy:   # Umbrel braucht diesen Proxy-Service!
    environment:
      APP_HOST: qubic-lite-ui
      APP_PORT: 8080

  qubic-lite-core:
    image: andyqus/qubic-lite-node:latest
    command: ["dotnet", "qubic-lite.core.dll"]
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:9090
      - ASPNETCORE_ENVIRONMENT=Production
      - TorProxy=socks5://tor:9050
      - OnionHostnamePath=/var/lib/tor/hidden_service/service1/hostname
      - DATA_DIR=/app/data
    volumes:
      - ${APP_DATA_DIR}/core-data:/app/data
    networks:
      - qubicnet

  qubic-lite-ui:
    image: andyqus/qubic-lite-node:latest
    command: ["dotnet", "qubic-lite.ui.dll"]
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - CORE_API_URL=http://qubic-lite-core:9090
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - qubic-lite-core
    networks:
      - qubicnet

networks:
  qubicnet:
    driver: bridge
