services:
  app_proxy:
    environment:
      APP_HOST: qubic-lite-node_edge
      APP_PORT: 8080
      PROXY_AUTH_ADD: "true"
      PROXY_AUTH_WHITELIST: "/api/*,/swagger/*"
    networks:
      - default
      - umbrel_main_network

  qubic-lite-node_edge:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on: 
      - qubic-lite-node_ui
      - qubic-lite-node_core
    volumes:
      - ${APP_DATA_DIR}/edge/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - umbrel_main_network
    # Zusätzliche DNS-Auflösung für Tor-Services
    extra_hosts:
      - "host.docker.internal:host-gateway"

  qubic-lite-node_core:
    image: andyqus/qubic-lite-node:core-v1.0.40
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:9090
      - ASPNETCORE_ENVIRONMENT=Production
      # Kritisch: Tor-Proxy Konfiguration
      - TorProxy=socks5://tor:9050
      - ASPNETCORE_DATAPROTECTION__KEYRING__PATH=/app/data/keys
      - ASPNETCORE_DATAPROTECTION__APPLICATIONNAME=QubicLite-Core
      - DATA_DIR=/app/data
      - OnionHostnamePath=/tor-host/hostname
      # Erweiterte Timeouts für Peer-Discovery
      - NETWORK_TIMEOUT=60000
      - TOR_CONNECTION_TIMEOUT=120000
      - PEER_DISCOVERY_TIMEOUT=180000
      # Logging für Debugging
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Information
      - ASPNETCORE_LOGGING__LOGLEVEL__MICROSOFT=Warning
    volumes:
      - ${APP_DATA_DIR}/core-data:/app/data
      - /home/umbrel/umbrel/tor/data/app-qubic-lite-node:/tor-host:ro
    healthcheck:
      test: ["CMD-SHELL", "wget --no-proxy -qO- http://127.0.0.1:9090/api/health > /dev/null || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 60s  # Mehr Zeit für Tor-Initialisierung
    networks:
      - default
      - umbrel_main_network
    # Kritisch für Container-zu-Container Kommunikation
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # WICHTIG: Erweiterte Capabilities
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    # Sicherheitskontext
    security_opt:
      - apparmor:unconfined
    # DNS für bessere Auflösung
    dns:
      - 127.0.0.11  # Docker's embedded DNS
      - 8.8.8.8
      - 1.1.1.1

  qubic-lite-node_ui:
    image: andyqus/qubic-lite-node:ui-v1.0.40
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_DATAPROTECTION__KEYRING__PATH=/app/data/keys
      - ASPNETCORE_DATAPROTECTION__APPLICATIONNAME=QubicLite-UI
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - CORE_API_URL=http://qubic-lite-node_core:9090
      - OnionHostnamePath=/tor-host/hostname
      - DATA_DIR=/app/data
    volumes:
      - ${APP_DATA_DIR}/ui-data:/app/data
      - /home/umbrel/umbrel/tor/data/app-qubic-lite-node:/tor-host:ro
    depends_on:
      qubic-lite-node_core:
        condition: service_healthy  # Warten auf gesunden Core-Service
    networks:
      - default
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true
    # Zusätzliche Netzwerk-Konfiguration
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"