services:
  app_proxy:
    environment:
      APP_HOST: qubic-lite-node_edge
      APP_PORT: 8080
      PROXY_AUTH_ADD: "true"
      PROXY_AUTH_WHITELIST: "/,/api/*,/swagger/*,/gossip/*"

  # qubic-lite-node_edge:
  #   image: nginx:1.27-alpine
  #   restart: unless-stopped
  #   depends_on: [qubic-lite-node_ui, qubic-lite-node_core]
  #   volumes:
  #     - ${APP_DATA_DIR}/edge/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   networks:
  #     - default
  #     - umbrel_main_network      # optional, schadet nicht

  # in deiner docker-compose.yml, Service: qubic-lite-node_edge
  qubic-lite-node_edge:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on: [qubic-lite-node_ui, qubic-lite-node_core]
    volumes:
      - ${APP_DATA_DIR}/edge/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      umbrel_main_network:
        aliases:
          - qubic-lite-node_edge   # <— wichtiger Alias für app_proxy
      default: {}

  qubic-lite-node_core:
    image: andyqus/qubic-lite-node:core-v1.0.56
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:9090
      - ASPNETCORE_ENVIRONMENT=Production
      - TorProxy=socks5://tor:9050
      - ASPNETCORE_DATAPROTECTION__KEYRING__PATH=/app/data/keys
      - ASPNETCORE_DATAPROTECTION__APPLICATIONNAME=QubicLite-Core
      - DATA_DIR=/app/data
      - OnionHostnamePath=/tor-host/hostname
    volumes:
      - ${APP_DATA_DIR}/core-data:/app/data
      - /home/umbrel/umbrel/tor/data/app-qubic-lite-node:/tor-host:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:9090/api/health > /dev/null || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 10
    networks:
      - default
      - umbrel_main_network      # WICHTIG!

  qubic-lite-node_ui:
    image: andyqus/qubic-lite-node:ui-v1.0.56
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_DATAPROTECTION__KEYRING__PATH=/app/data/keys
      - ASPNETCORE_DATAPROTECTION__APPLICATIONNAME=QubicLite-UI
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - CORE_API_URL=http://qubic-lite-node_core:9090
      - OnionHostnamePath=/tor-host/hostname
      - DATA_DIR=/app/data
    volumes:
      - ${APP_DATA_DIR}/ui-data:/app/data
      - /home/umbrel/umbrel/tor/data/app-qubic-lite-node:/tor-host:ro
    depends_on: [qubic-lite-node_core]
    networks:
      - default
      - umbrel_main_network      # optional

networks:
  # ❌ KEIN external hier! Umbrel erzeugt das default-Netz selbst.
  # ❌ Kein "name:" für default nötig.
  # default:  <-- diesen Block komplett weglassen

  # ✅ Nur das Umbrel-Main-Netz als external anhängen:
  umbrel_main_network:
    external: true
