manifestVersion: 1
id: "qubic-lite-node"
name: "Qubic LiteNode+"
tagline: "⚠️ Test version of the Qubic Lite Node dashboard"
icon: "https://raw.githubusercontent.com/AndyQus/umbrel-app-store-qubic-lite-node/main/qubic-lite-node/icon.svg"
category: "Productivity"
version: "0.1.0"
description: >-
  A lightweight node that synchronizes transactions and data from the Qubic network via Tor and provides a dashboard.

developer: "Andyqus"
website: "https://qubic.org"
repo: "https://github.com/AndyQus/umbrel-app-store-qubic-lite-node"
support: "https://github.com/AndyQus/umbrel-app-store-qubic-lite-node/issues"

# Hier sagst du Umbrel: 
# -> Dashboard (UI) auf 8089
# -> Core API auf 9090
ports:
  - id: ui
    target: 8080
    published: 8089
  - id: core
    target: 9090
    published: 9090

services:
  - id: core
    name: Qubic Core-Test
    image: andyqus/qubic-lite-node:latest
    command: ["dotnet", "core/qubic-lite.core.dll"]
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:9090"
      ASPNETCORE_ENVIRONMENT: "Production"
      DATA_DIR: "/app/data"
    volumes:
      - core-test-data:/app/data
    restart: on-failure

  - id: ui
    name: Qubic UI-Test
    image: andyqus/qubic-lite-node:latest
    command: ["dotnet", "ui/qubic-lite.ui.dll"]
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      CORE_API_URL: "http://core:9090"
      ASPNETCORE_ENVIRONMENT: "Production"
    depends_on:
      - core
    restart: on-failure

volumes:
  - core-data-test
