id: "qubic-lite-node-test"
name: "Qubic Lite Node (Test)"
category: "Productivity"
version: "0.1.0"
# tagline: "Blazor dashboard for Qubic Lite Node"
tagline: "⚠️ Test version of the Qubic Lite Node dashboard"
description: "A lightweight node that synchronizes transactions and data from the Qubic network via Tor and provides a dashboard."
developer: "Andyqus"
website: "https://qubic.org"
repo: "https://github.com/AndyQus/umbrel-app-store-qubic-lite-node"
support: "https://github.com/AndyQus/umbrel-app-store-qubic-lite-node/issues"
port: 8089
icon: "icon.svg"

services:
  - id: core
    name: Qubic Lite Core (Test)
    image: andyqus/qubic-lite-node:latest
    command: ["dotnet", "qubic-lite.core.dll"]
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:9090"
      ASPNETCORE_ENVIRONMENT: "Production"
      TorProxy: "socks5://tor:9050"
      OnionHostnamePath: "/var/lib/tor/hidden_service/service1/hostname"
      DATA_DIR: "/app/data"
    volumes:
      # - core-data:/app/data
      - core-test-data:/app/data
    restart: on-failure

  - id: ui
    name: Qubic Lite UI (Test)
    image: andyqus/qubic-lite-node:latest
    command: ["dotnet", "qubic-lite.ui.dll"]
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8089"
      CORE_API_URL: "http://core:9090"
      ASPNETCORE_ENVIRONMENT: "Production"
    depends_on:
      - core
    ports:
      - "8089:8089"
    restart: on-failure

volumes:
  # - core-data
  - core-test-data
